---
language: node.js
sudo: required

services:
  - docker

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - shellcheck

matrix:
  fast_finish: true

env:
  - TEST_RUN="./tests/test-kubeadm-dind-cluster.sh"
  - TEST_RUN="./tests/test-kubernetes.sh"

before_install:
  - npm install -g npm
  - npm install eslint
  - eslint --version
  - pip install -r test-requirements.txt

install:
  - "./scripts/install.sh"
  - "./scripts/bx_auth.sh"

before_script:
  - "./tests/test-javac.sh"
  - "./tests/test-shellcheck.sh"
  - "./tests/test-yamllint.sh"

script: "$TEST_RUN"
